version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: annotate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: annotatedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - annotate-net

  backend:
    build:
      context: ./Annotate
    container_name: annotate-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/annotatedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      FILE_UPLOAD_DIR: /uploads/videos
      FILE_UPLOAD_BASE_URL: http://localhost:8080
    volumes:
      - uploads:/uploads
    ports:
      - "8080:8080"
    networks:
      - annotate-net

  frontend:
    build:
      context: ./Annotate_Frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080/api
    container_name: annotate-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - annotate-net

volumes:
  postgres_data:
  uploads:

networks:
  annotate-net:
    driver: bridge
